USE FREE_VUE;
GO

SELECT * FROM SCREENINGS;
GO

-- Column names are unique so don't need FILMS.TITLE
SELECT DATE, TITLE, NAME FROM SCREENINGS 
INNER JOIN FILMS ON SCREENINGS.FILM_ID=FILMS.FILM_ID
INNER JOIN VENUES ON SCREENINGS.VENUE_ID=VENUES.VENUE_ID;
GO
